package base;

import java.io.Serializable;

public enum TerritoryType implements Serializable{

	ALASKA,ALBERTA,CENTRAL_AMERICA,EASTERN_UNITED_STATES,GREENLAND,NORTHWEST_TERRITORY,ONTARIO,QUEBEC,WESTERN_UNITED_STATES,
	ARGENTINA,BRAZIL,PERU,VENEZUELA,GREAT_BRITAIN,ICELAND,NORTHERN_EUROPE,SCANDINAVIA,SOUTHERN_EUROPE,UKRAINE,WESTERN_EUROPE,
	CENTRAL_AFRICA,EAST_AFRICA,EGYPT,MADAGASCAR,NORTH_AFRICA,SOUTH_AFRICA,AFGHANISTAN,CHINA,INDIA,IRKUTSK,JAPAN,
	KAMCHATKA,MIDDLE_EAST,MONGOLIA,SIAM,SIBERIA,URAL,YAKUTSK,EASTERN_AUSTRALIA,INDONESIA,NEW_GUINEA,WESTERN_AUSTRALIA,NONE;
	
}
